### ISSUE TITLE
There was an error when I tried to run the "classify" mode.

### ISSUE THREAD

**Issue by GiorgioPeng** [qitianwu/GraphOOD-GNNSafe#1]
I just changed the 'detect' mode to 'classify' mode
```
python main.py --method gnnsafe --backbone gcn --dataset cora --ood_type structure --mode classify --use_bn --device 1
```
Training, validation and testing processes are running properly.
However, I got the follow error:
```
Traceback (most recent call last):
  File "main.py", line 145, in <module>
    save_result(results, args)
  File "xx/GraphOOD-GNNSafe/GNNSafe/logger.py", line 164, in save_result
    for k in range(results.shape[1] // 3):
IndexError: tuple index out of range
```
It's just a slight mistake, but I think I need to tell you anyway.

**Comment by qitianwu** [comment]
Having fixed this bug. Thank you for letting me know!
